-- Agenda schema, version 1.
--
-- This file is the single source of truth for the database schema. It is applied by:
--   * the Tauri SQL plugin on desktop (apps/desktop/src-tauri embeds it with include_str!), and
--   * src/db/migrate.ts when running on sql.js in the browser or under vitest.
--
-- Conventions
--   * ids are UUID v4 strings generated by the app, never by the database.
--   * timestamps are ISO-8601 UTC strings ("2025-10-08T14:03:11.123Z"). The app sets them; the
--     defaults below are a safety net only.
--   * calendar dates (page_date, entry_date) are "YYYY-MM-DD" strings.
--   * JSON columns are TEXT. Repositories parse on read and stringify on write.
--   * booleans are INTEGER 0/1.
--   * every user-data table carries deleted_at (soft delete; repositories filter
--     `deleted_at IS NULL`) and version (bumped on every update) so that device sync can be
--     added later without a schema rewrite.
--   * PRAGMA foreign_keys is enabled per connection by the adapters, not here, because a PRAGMA
--     inside a migration transaction is a no-op.

CREATE TABLE profiles (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  settings    TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at  TEXT,
  version     INTEGER NOT NULL DEFAULT 1
);

-- A well-known default profile so a fresh install (and every device) starts with the same one.
INSERT INTO profiles (id, name) VALUES ('00000000-0000-4000-8000-000000000001', 'Default');

CREATE TABLE planners (
  id               TEXT PRIMARY KEY,
  profile_id       TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name             TEXT NOT NULL,
  description      TEXT,
  planner_settings TEXT NOT NULL DEFAULT '{}',
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at       TEXT,
  version          INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_planners_profile ON planners(profile_id);

CREATE TABLE page_templates (
  id              TEXT PRIMARY KEY,
  planner_id      TEXT NOT NULL REFERENCES planners(id) ON DELETE CASCADE,
  profile_id      TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  template_type   TEXT NOT NULL,
  is_default      INTEGER NOT NULL DEFAULT 0,
  content         TEXT NOT NULL,
  schema_version  INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at      TEXT,
  version         INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_templates_lookup ON page_templates(planner_id, template_type, is_default);

CREATE TABLE pages (
  id                 TEXT PRIMARY KEY,
  planner_id         TEXT NOT NULL REFERENCES planners(id) ON DELETE CASCADE,
  profile_id         TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  page_template_id   TEXT NOT NULL REFERENCES page_templates(id),
  page_type          TEXT NOT NULL,
  period_identifier  TEXT NOT NULL,
  page_date          TEXT NOT NULL,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at         TEXT,
  version            INTEGER NOT NULL DEFAULT 1,
  UNIQUE (planner_id, page_type, period_identifier)
);

CREATE TABLE planner_entries (
  id          TEXT PRIMARY KEY,
  page_id     TEXT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  planner_id  TEXT NOT NULL REFERENCES planners(id) ON DELETE CASCADE,
  profile_id  TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  tiptap_id   TEXT NOT NULL,
  entry_date  TEXT NOT NULL,
  content     TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at  TEXT,
  version     INTEGER NOT NULL DEFAULT 1,
  UNIQUE (page_id, tiptap_id)
);
CREATE INDEX idx_entries_page_date ON planner_entries(page_id, entry_date);

CREATE TABLE tldraw_snapshots (
  id          TEXT PRIMARY KEY,
  page_id     TEXT NOT NULL UNIQUE REFERENCES pages(id) ON DELETE CASCADE,
  planner_id  TEXT NOT NULL REFERENCES planners(id) ON DELETE CASCADE,
  profile_id  TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  document    TEXT NOT NULL,
  schema      TEXT,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at  TEXT,
  version     INTEGER NOT NULL DEFAULT 1
);

-- Calendar events. Same columns as the Rust migration plus external_id / calendar_id for the
-- planned external calendar sync. No application code uses this table yet.
CREATE TABLE events (
  id                    TEXT PRIMARY KEY,
  planner_id            TEXT NOT NULL REFERENCES planners(id) ON DELETE CASCADE,
  profile_id            TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title                 TEXT NOT NULL,
  description           TEXT,
  start_time            TEXT NOT NULL,
  end_time              TEXT NOT NULL,
  all_day               INTEGER NOT NULL DEFAULT 0,
  timezone              TEXT,
  recurrence_rule       TEXT,
  recurrence_exceptions TEXT,
  recurrence_end        TEXT,
  color                 TEXT,
  is_exception          INTEGER,
  original_start        TEXT,
  status                TEXT,
  source                TEXT,
  external_id           TEXT,
  calendar_id           TEXT,
  created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at            TEXT,
  version               INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_events_planner_start ON events(planner_id, start_time);
