//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub all_day: bool,
    pub timezone: Option<String>,
    pub recurrence_rule: Option<String>,
    pub recurrence_exceptions: Option<Json>,
    pub recurrence_end: Option<DateTime>,
    pub color: Option<String>,
    pub is_exception: Option<bool>,
    pub original_start: Option<DateTime>,
    pub status: Option<String>,
    pub source: Option<String>,
    pub events: String,
    pub planner_id: String,
    pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::planners::Entity",
        from = "Column::PlannerId",
        to = "super::planners::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Planners,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::planners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Planners.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
