//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pages")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub page_date: Date,
    pub page_type: String,
    pub period_identifier: String,
    pub updated_version: Option<i32>,
    pub user_id: String,
    pub planner_id: String,
    pub page_template_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::page_templates::Entity",
        from = "Column::PageTemplateId",
        to = "super::page_templates::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PageTemplates,
    #[sea_orm(has_many = "super::planner_entries::Entity")]
    PlannerEntries,
    #[sea_orm(
        belongs_to = "super::planners::Entity",
        from = "Column::PlannerId",
        to = "super::planners::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Planners,
    #[sea_orm(has_many = "super::tldraw_snapshots::Entity")]
    TldrawSnapshots,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::page_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageTemplates.def()
    }
}

impl Related<super::planner_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlannerEntries.def()
    }
}

impl Related<super::planners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Planners.def()
    }
}

impl Related<super::tldraw_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TldrawSnapshots.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
