//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    #[sea_orm(unique)]
    pub api_key: String,
    pub planners_count: Option<i32>,
    pub name: String,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub magic_link_token: Option<String>,
    pub magic_link_expiration: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::events::Entity")]
    Events,
    #[sea_orm(has_many = "super::page_templates::Entity")]
    PageTemplates,
    #[sea_orm(has_many = "super::pages::Entity")]
    Pages,
    #[sea_orm(has_many = "super::planner_entries::Entity")]
    PlannerEntries,
    #[sea_orm(has_many = "super::planners::Entity")]
    Planners,
    #[sea_orm(has_many = "super::tldraw_snapshots::Entity")]
    TldrawSnapshots,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::page_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageTemplates.def()
    }
}

impl Related<super::pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pages.def()
    }
}

impl Related<super::planner_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlannerEntries.def()
    }
}

impl Related<super::planners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Planners.def()
    }
}

impl Related<super::tldraw_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TldrawSnapshots.def()
    }
}
