import { createFileRoute } from '@tanstack/react-router'
import '../styles/styles.css'
import TiptapMonthly from '../components/monthly/TiptapMonthly'
import Monthly from '../components/monthly/Monthly'

export const Route = createFileRoute('/')({
  component: Index,
})

function Index() {
  return (
    <div className="planner-container">
      <div className="month-name">January 2025</div>
      <section className="monthly-week-header">
        <div>Sunday</div>
        <div>Monday</div>
        <div>Tuesday</div>
        <div>Wednesday</div>
        <div>Thursday</div>
        <div>Friday</div>
        <div>Saturday</div>
      </section>
      <section className="monthly-layout">
        <TiptapMonthly
          tiptap_id="1"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="2"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="3"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="4"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="5"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="6"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="7"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="8"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="9"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="10"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="11"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="12"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="13"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="14"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="15"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="16"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="17"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="18"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="19"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="20"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="21"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="22"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="23"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="24"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="25"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="26"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="27"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="28"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="29"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="30"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="31"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="32"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="33"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="34"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="35"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="36"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="37"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="38"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="39"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="40"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="41"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
        <TiptapMonthly
          tiptap_id="42"
          pageId=""
          className="monthly-day-cell-tiptap-main"
        />
      </section>
    </div>
  )
}