/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PlannersRouteImport } from './routes/planners'
import { Route as PlannersPlannerIdRouteImport } from './routes/planners.$plannerId'
import { Route as PlannersCreateRouteImport } from './routes/planners.create'
import { Route as TemplatesEditorRouteImport } from './routes/templates.editor'
import { Route as UsersCreateRouteImport } from './routes/users.create'
import { Route as PlannersPlannerIdMonthlyMonthIdRouteImport } from './routes/planners.$plannerId.monthly.$monthId'
import { Route as PlannersPlannerIdWeeklyWeekIdRouteImport } from './routes/planners.$plannerId.weekly.$weekId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannersRoute = PlannersRouteImport.update({
  id: '/planners',
  path: '/planners',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannersPlannerIdRoute = PlannersPlannerIdRouteImport.update({
  id: '/$plannerId',
  path: '/$plannerId',
  getParentRoute: () => PlannersRoute,
} as any)
const PlannersCreateRoute = PlannersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PlannersRoute,
} as any)
const TemplatesEditorRoute = TemplatesEditorRouteImport.update({
  id: '/templates/editor',
  path: '/templates/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannersPlannerIdMonthlyMonthIdRoute =
  PlannersPlannerIdMonthlyMonthIdRouteImport.update({
    id: '/monthly/$monthId',
    path: '/monthly/$monthId',
    getParentRoute: () => PlannersPlannerIdRoute,
  } as any)
const PlannersPlannerIdWeeklyWeekIdRoute =
  PlannersPlannerIdWeeklyWeekIdRouteImport.update({
    id: '/weekly/$weekId',
    path: '/weekly/$weekId',
    getParentRoute: () => PlannersPlannerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/planners': typeof PlannersRouteWithChildren
  '/planners/$plannerId': typeof PlannersPlannerIdRouteWithChildren
  '/planners/create': typeof PlannersCreateRoute
  '/templates/editor': typeof TemplatesEditorRoute
  '/users/create': typeof UsersCreateRoute
  '/planners/$plannerId/monthly/$monthId': typeof PlannersPlannerIdMonthlyMonthIdRoute
  '/planners/$plannerId/weekly/$weekId': typeof PlannersPlannerIdWeeklyWeekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/planners': typeof PlannersRouteWithChildren
  '/planners/$plannerId': typeof PlannersPlannerIdRouteWithChildren
  '/planners/create': typeof PlannersCreateRoute
  '/templates/editor': typeof TemplatesEditorRoute
  '/users/create': typeof UsersCreateRoute
  '/planners/$plannerId/monthly/$monthId': typeof PlannersPlannerIdMonthlyMonthIdRoute
  '/planners/$plannerId/weekly/$weekId': typeof PlannersPlannerIdWeeklyWeekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/planners': typeof PlannersRouteWithChildren
  '/planners/$plannerId': typeof PlannersPlannerIdRouteWithChildren
  '/planners/create': typeof PlannersCreateRoute
  '/templates/editor': typeof TemplatesEditorRoute
  '/users/create': typeof UsersCreateRoute
  '/planners/$plannerId/monthly/$monthId': typeof PlannersPlannerIdMonthlyMonthIdRoute
  '/planners/$plannerId/weekly/$weekId': typeof PlannersPlannerIdWeeklyWeekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/planners'
    | '/planners/$plannerId'
    | '/planners/create'
    | '/templates/editor'
    | '/users/create'
    | '/planners/$plannerId/monthly/$monthId'
    | '/planners/$plannerId/weekly/$weekId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/planners'
    | '/planners/$plannerId'
    | '/planners/create'
    | '/templates/editor'
    | '/users/create'
    | '/planners/$plannerId/monthly/$monthId'
    | '/planners/$plannerId/weekly/$weekId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/planners'
    | '/planners/$plannerId'
    | '/planners/create'
    | '/templates/editor'
    | '/users/create'
    | '/planners/$plannerId/monthly/$monthId'
    | '/planners/$plannerId/weekly/$weekId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlannersRoute: typeof PlannersRouteWithChildren
  TemplatesEditorRoute: typeof TemplatesEditorRoute
  UsersCreateRoute: typeof UsersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planners': {
      id: '/planners'
      path: '/planners'
      fullPath: '/planners'
      preLoaderRoute: typeof PlannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planners/$plannerId': {
      id: '/planners/$plannerId'
      path: '/$plannerId'
      fullPath: '/planners/$plannerId'
      preLoaderRoute: typeof PlannersPlannerIdRouteImport
      parentRoute: typeof PlannersRoute
    }
    '/planners/create': {
      id: '/planners/create'
      path: '/create'
      fullPath: '/planners/create'
      preLoaderRoute: typeof PlannersCreateRouteImport
      parentRoute: typeof PlannersRoute
    }
    '/templates/editor': {
      id: '/templates/editor'
      path: '/templates/editor'
      fullPath: '/templates/editor'
      preLoaderRoute: typeof TemplatesEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planners/$plannerId/monthly/$monthId': {
      id: '/planners/$plannerId/monthly/$monthId'
      path: '/monthly/$monthId'
      fullPath: '/planners/$plannerId/monthly/$monthId'
      preLoaderRoute: typeof PlannersPlannerIdMonthlyMonthIdRouteImport
      parentRoute: typeof PlannersPlannerIdRoute
    }
    '/planners/$plannerId/weekly/$weekId': {
      id: '/planners/$plannerId/weekly/$weekId'
      path: '/weekly/$weekId'
      fullPath: '/planners/$plannerId/weekly/$weekId'
      preLoaderRoute: typeof PlannersPlannerIdWeeklyWeekIdRouteImport
      parentRoute: typeof PlannersPlannerIdRoute
    }
  }
}

interface PlannersPlannerIdRouteChildren {
  PlannersPlannerIdMonthlyMonthIdRoute: typeof PlannersPlannerIdMonthlyMonthIdRoute
  PlannersPlannerIdWeeklyWeekIdRoute: typeof PlannersPlannerIdWeeklyWeekIdRoute
}

const PlannersPlannerIdRouteChildren: PlannersPlannerIdRouteChildren = {
  PlannersPlannerIdMonthlyMonthIdRoute: PlannersPlannerIdMonthlyMonthIdRoute,
  PlannersPlannerIdWeeklyWeekIdRoute: PlannersPlannerIdWeeklyWeekIdRoute,
}

const PlannersPlannerIdRouteWithChildren =
  PlannersPlannerIdRoute._addFileChildren(PlannersPlannerIdRouteChildren)

interface PlannersRouteChildren {
  PlannersPlannerIdRoute: typeof PlannersPlannerIdRouteWithChildren
  PlannersCreateRoute: typeof PlannersCreateRoute
}

const PlannersRouteChildren: PlannersRouteChildren = {
  PlannersPlannerIdRoute: PlannersPlannerIdRouteWithChildren,
  PlannersCreateRoute: PlannersCreateRoute,
}

const PlannersRouteWithChildren = PlannersRoute._addFileChildren(
  PlannersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlannersRoute: PlannersRouteWithChildren,
  TemplatesEditorRoute: TemplatesEditorRoute,
  UsersCreateRoute: UsersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
